AWSTemplateFormatVersion: '2010-09-09'
Description: "Perforce-server-main-template"
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "Perforce Server Configuration"
        Parameters: 
          - InstanceType
          - KeyPairName
          - DepotVolumeType
          - DepotVolumeSize
          - LogVolumeSize
          - MetadataVolumeType
          - MetadataVolumeSize
          - MetadataProvisionedIops
          - LatestAmiId
          - EnableReplica
      - Label:
          default: "AWS Quick Start Configuration"
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels: 
      InstanceType: 
        default: "Instance Type"
      KeyPairName:
        default: "Key Pair Name"
      DepotVolumeType:
        default: "Volume Type for Depot"
      DepotVolumeSize:
        default: "Volume Size for Depot"
      LogVolumeSize:
        default: "Volume Size for Log"
      MetadataVolumeType:
        default: "Volume Type for Metadata"
      MetadataVolumeSize:
        default: "Volume Size for Metadata"
      MetadataProvisionedIops:
        default: "Provisioned IOPS for Metadata Volume"
      LatestAmiId:
        default: "Latest AMI ID for Amazon Linux2"
      EnableReplica:
        default: "Enable Replica"
      QSS3BucketName:
        default: "Quick Start S3 Bucket Name"
      QSS3BucketRegion:
        default: "Quick Start S3 bucket region"
      QSS3KeyPrefix:
        default: "Quick Start S3 Key Prefix"

Parameters: 
  InstanceType: 
    Type: String
    Default: c5.4xlarge
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
    Description: "Select Perforce server EC2 instance type. Default is c5.4xlarge."
  KeyPairName:
    Description: "Public/private key pairs allow you to securely connect to your instance after it launches"
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  EnableReplica:
    Type: String
    Default: "No"
    AllowedValues: 
      - "Yes"
      - "No"
    Description: "If you build Perforce Replica Server, select Yes. Replica Server will be the same setting as Master server."
  DepotVolumeType:
    Type: String
    Default: st1
    AllowedValues: 
      - st1
      - gp2
    Description: "Select either ST1 or GP2."
  DepotVolumeSize:
    Type: String
    Default: '1024'
    Description: "The size of the EBS volume attached for Depot."
  LogVolumeSize:
    Type: String
    Default: '128'
    Description: "The size of the EBS volume attached for Log."
  MetadataVolumeType:
    Type: String
    Default: gp2
    AllowedValues: 
      - gp2
      - io1
    Description: "Select either GP2 or IO1."
  MetadataVolumeSize:
    Type: String
    Default: '64'
    Description: "The size of the EBS volume attached for Metadata."
  MetadataProvisionedIops:
    ConstraintDescription: "Range is 100 to 64000 for Provisioned IOPS SSD volumes."
    Description: "Set the provisioned IOPs between 100 and 64000. Only set if you are choosing io1 for your metadata volume type."
    Type: "String"

Conditions: 
  CreateReplicaServer: !Equals [ !Ref EnableReplica, "Yes" ]

Resources:
  PerforceVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://aws-hori.s3-ap-northeast-1.amazonaws.com/perforce/aws-perforce/templates/PerforceServerVPCTemplate.yaml"
      Parameters:
        EnableReplica: !Ref EnableReplica

  # Create Perforce master server
  PerforceMasterServerInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://aws-hori.s3-ap-northeast-1.amazonaws.com/perforce/aws-perforce/templates/PerforceServersSetupCloudFormationTemplate.yaml"
      Parameters:
        PerforceAZ: !Select 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'      
        LatestAmiId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        ServerName: "p4-awsnva-01"
        ServerDescription: "Master/commit server. The master.1 is the SDP instance name, a data set identifier."
        ServerID: "master.1" 
        DepotVolumeType: !Ref DepotVolumeType
        DepotVolumeSize: !Ref DepotVolumeSize
        LogVolumeSize: !Ref LogVolumeSize
        MetadataVolumeType: !Ref MetadataVolumeType
        MetadataVolumeSize: !Ref MetadataVolumeSize
        MetadataProvisionedIops: !Ref MetadataProvisionedIops
        SubnetId: !GetAtt PerforceVPCStack.Outputs.PerforceMasterSubnetId
        PrivateIpAddress: 10.0.0.63
        PerforceSecurityGroup: !GetAtt PerforceVPCStack.Outputs.PerforceSecurityGroupId
        gw1: !GetAtt PerforceVPCStack.Outputs.PerforceVPCGatewaySettingID
  # Create Perforce replica server if needed
  PerforceReplicaServerInstance:
    Type: AWS::CloudFormation::Stack
    Condition: CreateReplicaServer
    Properties:
      TemplateURL: "https://aws-hori.s3-ap-northeast-1.amazonaws.com/perforce/aws-perforce/templates/PerforceServersSetupCloudFormationTemplate.yaml"
      Parameters:
        PerforceAZ: !Select 
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
        LatestAmiId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        ServerName: "p4-awsnva-02"
        ServerDescription: "Replica server. The p4d-ha-awsnva is the SDP instance name, a data set identifier."
        ServerID: "p4d-ha-awsnva"
        DepotVolumeType: !Ref DepotVolumeType
        DepotVolumeSize: !Ref DepotVolumeSize
        LogVolumeSize: !Ref LogVolumeSize
        MetadataVolumeType: !Ref MetadataVolumeType
        MetadataVolumeSize: !Ref MetadataVolumeSize
        MetadataProvisionedIops: !Ref MetadataProvisionedIops
        SubnetId: !GetAtt PerforceVPCStack.Outputs.PerforceReplicaSubnetId
        PrivateIpAddress: 10.0.1.63
        PerforceSecurityGroup: !GetAtt PerforceVPCStack.Outputs.PerforceSecurityGroupId
        gw1: !GetAtt PerforceVPCStack.Outputs.PerforceVPCGatewaySettingID

Outputs:
  PerforceMasterInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !GetAtt PerforceMasterServerInstance.Outputs.EC2InstanceId
  PerforceReplicaInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !GetAtt PerforceReplicaServerInstance.Outputs.EC2InstanceId
