AWSTemplateFormatVersion: '2010-09-09'
Description: "Perforce-server-master-template"
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "Perforce Server Configuration"
        Parameters: 
          - InstanceType
          - KeyPairName
          - DepotVolumeType
          - DepotVolumeSize
          - LogVolumeSize
          - MetadataVolumeType
          - MetadataVolumeSize
          - MetadataProvisionedIops
          - LatestAmiId
          - EnableReplica
      - Label:
          default: "AWS Quick Start Configuration"
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels: 
      InstanceType: 
        default: "Instance Type"
      KeyPairName:
        default: "Key Pair Name"
      DepotVolumeType:
        default: "Volume Type for Depot"
      DepotVolumeSize:
        default: "Volume Size for Depot"
      LogVolumeSize:
        default: "Volume Size for Log"
      MetadataVolumeType:
        default: "Volume Type for Metadata"
      MetadataVolumeSize:
        default: "Volume Size for Metadata"
      MetadataProvisionedIops:
        default: "Provisioned IOPS for Metadata Volume"
      LatestAmiId:
        default: "Latest AMI ID for Amazon Linux2"
      EnableReplica:
        default: "Enable Replica"
      QSS3BucketName:
        default: "Quick Start S3 Bucket Name"
      QSS3BucketRegion:
        default: "Quick Start S3 bucket region"
      QSS3KeyPrefix:
        default: "Quick Start S3 Key Prefix"

Parameters: 
  InstanceType: 
    Type: String
    Default: c5.4xlarge
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
    Description: "Select Perforce server EC2 instance type. Default is c5.4xlarge."
  KeyPairName:
    Description: "Public/private key pairs allow you to securely connect to your instance after it launches"
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  EnableReplica:
    Type: String
    Default: "No"
    AllowedValues: 
      - "Yes"
      - "No"
    Description: "If you build Perforce Replica Server, select Yes. Replica Server will be the same setting as Master server."
  DepotVolumeType:
    Type: String
    Default: st1
    AllowedValues: 
      - st1
      - gp2
    Description: "Select either ST1 or GP2."
  DepotVolumeSize:
    Type: String
    Default: '1024'
    Description: "The size of the EBS volume attached for Depot."
  LogVolumeSize:
    Type: String
    Default: '128'
    Description: "The size of the EBS volume attached for Log."
  MetadataVolumeType:
    Type: String
    Default: gp2
    AllowedValues: 
      - gp2
      - io1
    Description: "Select either GP2 or IO1."
  MetadataVolumeSize:
    Type: String
    Default: '64'
    Description: "The size of the EBS volume attached for Metadata."
  MetadataProvisionedIops:
    ConstraintDescription: "Range is 100 to 64000 for Provisioned IOPS SSD volumes."
    Description: "Set the provisioned IOPs between 100 and 64000. Only set if you are choosing io1 for your metadata volume type."
    Type: "String"

Conditions: 
  CreateReplicaServer: !Equals [ !Ref EnableReplica, "Yes" ]

Resources:
  PerforceVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'false'
      Tags:
      - Key: Name
        Value: Perforce
  PerforcePublicSubnetMaster:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId:
        Ref: PerforceVPC
      Tags:
      - Key: Name
        Value: Perforce-Public-Subnet-Master
  PerforcePublicSubnetReplica:
    Type: AWS::EC2::Subnet
    Condition: CreateReplicaServer
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId:
        Ref: PerforceVPC
      Tags:
      - Key: Name
        Value: Perforce-Public-Subnet-Replica
  PerforceIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Public-Perforce
  dopt06d06862:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: ap-northeast-1.compute.internal
      DomainNameServers:
      - AmazonProvidedDNS
  PerforceNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: PerforceVPC
  PerforceRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: PerforceVPC

  VolumeHxlogsMaster:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-northeast-1a
      Size:
        Ref: LogVolumeSize
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: p4-awsnva-01-hxlogs
      - Key: ServerID
        Value: master.1
  VolumeHxdepotsMaster:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-northeast-1a
      Encrypted: true
      Size:
        Ref: DepotVolumeSize
      VolumeType:
        Ref: DepotVolumeType
      Tags:
      - Key: ServerID
        Value: master.1
      - Key: Name
        Value: p4-awsnva-01-hxdepots
  VolumeHxmetadataMaster:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-northeast-1a
      Size:
        Ref: MetadataVolumeSize
      VolumeType:
        Ref: MetadataVolumeType
      Iops:
        Ref: MetadataProvisionedIops
      Tags:
      - Key: Name
        Value: p4-awsnva-01-hxmetadata
      - Key: ServerID
        Value: master.1
  VolumeHxlogsReplica:
    Type: AWS::EC2::Volume
    Condition: CreateReplicaServer
    Properties:
      AvailabilityZone: ap-northeast-1c
      Size:
        Ref: LogVolumeSize
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: p4-awsnva-02-hxlogs
      - Key: ServerID
        Value: p4d-ha-awsnva
  VolumeHxdepotsReplica:
    Type: AWS::EC2::Volume
    Condition: CreateReplicaServer
    Properties:
      AvailabilityZone: ap-northeast-1c
      Encrypted: true
      Size:
        Ref: DepotVolumeSize
      VolumeType:
        Ref: DepotVolumeType
      Tags:
      - Key: ServerID
        Value: p4d-ha-awsnva
      - Key: Name
        Value: p4-awsnva-02-hxdepots
  VolumeHxmetadataReplica:
    Type: AWS::EC2::Volume
    Condition: CreateReplicaServer
    Properties:
      AvailabilityZone: ap-northeast-1c
      Size:
        Ref: MetadataVolumeSize
      VolumeType:
        Ref: MetadataVolumeType
      Iops:
        Ref: MetadataProvisionedIops
      Tags:
      - Key: Name
        Value: p4-awsnva-02-hxmetadata
      - Key: ServerID
        Value: p4d-ha-awsnva
  sgPerforceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This security group is for Perforce.
      VpcId:
        Ref: PerforceVPC
  acl1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId:
        Ref: PerforceNACL
  acl2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId:
        Ref: PerforceNACL
  subnetacl1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PerforceNACL
      SubnetId:
        Ref: PerforcePublicSubnetMaster
  subnetacl2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Condition: CreateReplicaServer
    Properties:
      NetworkAclId:
        Ref: PerforceNACL
      SubnetId:
        Ref: PerforcePublicSubnetReplica
  gw1:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: PerforceVPC
      InternetGatewayId:
        Ref: PerforceIGW
  route1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: PerforceRouteTable
      GatewayId:
        Ref: PerforceIGW
    DependsOn: gw1
  subnetrtbassoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: PerforceRouteTable
      SubnetId:
        Ref: PerforcePublicSubnetMaster
  subnetrtbassoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateReplicaServer
    Properties: 
      RouteTableId:
        Ref: PerforceRouteTable
      SubnetId:
        Ref: PerforcePublicSubnetReplica
  dchpassoc1:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId:
        Ref: PerforceVPC
      DhcpOptionsId:
        Ref: dopt06d06862
  ingress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
  ingress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      CidrIp: 0.0.0.0/0
  ingress3:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: tcp
      FromPort: '1666'
      ToPort: '1666'
      CidrIp: 0.0.0.0/0
  egress1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
  # Create Perforce master server
  PerforceMasterServerInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://aws-hori.s3-ap-northeast-1.amazonaws.com/perforce/aws-perforce/templates/PerforceServersSetupCloudFormationTemplate.yaml"
      Parameters:
        LatestAmiId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        ServerName: "p4-awsnva-01"
        ServerDescription: "Master/commit server. The master.1 is the SDP instance name, a data set identifier."
        ServerID: "master.1"
        VolumeHxdepots: !Ref VolumeHxdepotsMaster
        VolumeHxlogs: !Ref VolumeHxlogsMaster
        VolumeHxmetadata: !Ref VolumeHxmetadataMaster
        SubnetId: !Ref PerforcePublicSubnetMaster
        PrivateIpAddress: 10.0.0.63
        PerforceSecurityGroup: !Ref sgPerforceSG
        gw1: !Ref gw1
  # Create Perforce replica server if needed
  PerforceReplicaServerInstance:
    Type: AWS::CloudFormation::Stack
    Condition: CreateReplicaServer
    Properties:
      TemplateURL: "https://aws-hori.s3-ap-northeast-1.amazonaws.com/perforce/aws-perforce/templates/PerforceServersSetupCloudFormationTemplate.yaml"
      Parameters:
        LatestAmiId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        ServerName: "p4-awsnva-02"
        ServerDescription: "Replica server. The p4d-ha-awsnva is the SDP instance name, a data set identifier."
        ServerID: "p4d-ha-awsnva"
        VolumeHxdepots: !Ref VolumeHxdepotsReplica
        VolumeHxlogs: !Ref VolumeHxlogsReplica
        VolumeHxmetadata: !Ref VolumeHxmetadataReplica
        SubnetId: !Ref PerforcePublicSubnetReplica
        PrivateIpAddress: 10.0.1.63
        PerforceSecurityGroup: !Ref sgPerforceSG
        gw1: !Ref gw1
