AWSTemplateFormatVersion: '2010-09-09'
Resources:
  vpc089014ea9c553180d:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'false'
      Tags:
      - Key: Name
        Value: Perforce
  subnet04731f3d427d1b04f:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId:
        Ref: vpc089014ea9c553180d
      Tags:
      - Key: Name
        Value: Perforce-Public-Subnet
  igw06ff7ac884deea506:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Public-Perforce
  dopt06d06862:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: ap-northeast-1.compute.internal
      DomainNameServers:
      - AmazonProvidedDNS
  acl0dc84171401f0d22f:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: vpc089014ea9c553180d
  rtb04fd13c1658e30807:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: vpc089014ea9c553180d
  eip1817754170:
    Type: AWS::EC2::EIP
    DependsOn:
    - gw1
    Properties:
      Domain: vpc
  instancei094428780f474b671:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      EbsOptimized: 'true'
      ImageId: ami-011facbea5ec0363b
      InstanceType: c5.4xlarge
      KeyName: general-key
      Monitoring: 'true'
      Tags:
      - Key: Name
        Value: p4-awsnva-01
      - Key: Description
        Value: Master/commit server. The .1 is the SDP instance name, a data set identifier.
      - Key: ServerID
        Value: master.1
      Volumes:
      - Device: /dev/sdb
        VolumeId:
          Ref: VolumeHxdepots
      - Device: /dev/sdc
        VolumeId:
          Ref: VolumeHxlogs
      - Device: /dev/sdd
        VolumeId:
          Ref: VolumeHxmetadata
      NetworkInterfaces:
      - DeleteOnTermination: 'true'
        Description: Primary network interface
        DeviceIndex: 0
        SubnetId:
          Ref: subnet04731f3d427d1b04f
        PrivateIpAddresses:
        - PrivateIpAddress: 10.0.0.63
          Primary: 'true'
        GroupSet:
        - Ref: sgPerforceSG
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          # Install packages 
          yum -y update

          yum -y install aws-cfn-bootstrap
          # Install the files and packages from the metadata
          # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/cfn-init.html
          /opt/aws/bin/cfn-init -v --configsets default --stack ${AWS::StackName} --resource instancei094428780f474b671 --region ${AWS::Region}
          # Signal the status from cfn-init
          # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/cfn-signal.html
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource instancei094428780f474b671 --region ${AWS::Region} 

    Metadata:
      # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
      AWS::CloudFormation::Init:
        configSets: 
          default: 
            - "01_config_setup_volumes"
            - "02_config_setup_yum_repo"
            - "03_config_helix-p4d"
            - "04_config_install_sdp"
            - "05_config_start_helix-p4d"
        01_config_setup_volumes:
          commands:
            # Mount hxdepots
            01_setup_hxdepots:
              command: "mkfs -t xfs /dev/sdb && mkdir /hxdepots && mount /dev/sdb /hxdepots"
              ignoreErrors: false
            # Mount hxlogs
            02_setup_hxlogs:
              command: "mkfs -t xfs /dev/sdc && mkdir /hxlogs && mount /dev/sdc /hxlogs"
              ignoreErrors: false
            # Mount hxmetadata
            03_setup_hxmetadata:
              command: "mkfs -t xfs /dev/sdd && mkdir /hxmetadata && mount /dev/sdd /hxmetadata"
              ignoreErrors: false
            # Configure /etc/fstab
        02_config_setup_yum_repo:
          # Add yum repository
          files: 
            /etc/yum.repos.d/perforce.repo: 
              content: !Sub | 
                [perforce]
                name=Perforce
                baseurl=http://package.perforce.com/yum/rhel/7/x86_64/
                enabled=1
                gpgcheck=1
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            01_import_pubkey:
              command: "rpm --import https://package.perforce.com/perforce.pubkey"
              ignoreErrors: false
        03_config_helix-p4d:
          packages:
            yum:
              helix-p4d: []
          commands:
            01_adduser_p4admin:
              command: "adduser -g perforce -G adm,wheel p4admin"
              ignoreErrors: false
            02_mkdir_p4admin_dir:
              command: "mkdir /home/p4admin/.ssh"
              ignoreErrors: false
            03_cp_key:
              command: "cp /home/ec2-user/.ssh/authorized_keys /home/p4admin/.ssh"
              ignoreErrors: false
            04_chown:
              command: "chown p4admin:perforce --recursive /home/p4admin/.ssh"
              ignoreErrors: false
            05_chmod:
              command: "chmod 700 /home/p4admin/.ssh"
              ignoreErrors: false
            06_chmod:
              command: "chmod 600 /home/p4admin/.ssh/authorized_keys"
              ignoreErrors: false
            07_allow_p4admin_sudo:
              command: "echo 'p4admin         ALL=(ALL)       NOPASSWD: ALL' >> /etc/sudoers"
              ignoreErrors: false
        04_config_install_sdp:
          sources:
            /tmp: "https://swarm.workshop.perforce.com/projects/perforce-software-sdp/download/downloads/sdp.Unix.2019.3.26239.tgz"
          commands:
            01_mv_sdp:
              command: "mv /tmp/sdp /hxdepots"
              ignoreErrors: false
            02_backup_config:
              command: "cp /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg.bak"
              ignoreErrors: false
            03_rewrite_config:
              command: "sudo sed -i -e 's/DB1=.*/DB1=hxmetadata/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            04_rewrite_config:
              command: "sed -i -e 's/DB2=.*/DB2=hxmetadata/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            05_rewrite_config:
              command: "sed -i -e 's/DD=.*/DD=hxdepots/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            06_rewrite_config:
              command: "sed -i -e 's/LG=.*/LG=hxlogs/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            07_rewrite_config:
              command: "sed -i -e 's/OSUSER=.*/OSUSER=p4admin/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            08_rewrite_config:
              command: "sed -i -e 's/OSGROUP=.*/OSGROUP=perforce/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            09_rewrite_config:
              command: "sed -i -e 's/MAILHOST=.*/MAILHOST=localhost/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            10_rewrite_config:
              command: "sed -i -e 's/SSL_PREFIX=.*/SSL_PREFIX=/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            11_rewrite_config:
              command: "sed -i -e 's/P4DNSNAME=.*/P4DNSNAME=ip-10-0-0-63.ap-northeast-1.compute.internal/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            12_rewrite_config:
              command: "sed -i -e 's/COMPLAINFROM_DOMAIN=.*/COMPLAINFROM_DOMAIN=amazonaws.com/g' /hxdepots/sdp/Server/Unix/setup/mkdirs.cfg"
              ignoreErrors: false
            13_create_symlink:
              command: "ln -s /opt/perforce/bin/p4 /hxdepots/sdp/Server/Unix/p4/common/bin/p4"
              ignoreErrors: false
            14_create_symlink:
              command: "ln -s /opt/perforce/sbin/p4d /hxdepots/sdp/Server/Unix/p4/common/bin/p4d"
              ignoreErrors: false
            15_setup_sdp:
              command: "/hxdepots/sdp/Server/Unix/setup/mkdirs.sh 1"
              ignoreErrors: false
        05_config_start_helix-p4d:
          files: 
            /etc/systemd/system/p4d_1.service: 
              content: !Sub | 
                [Unit]
                Description=Helix Server Instance 1
                Documentation=http://www.perforce.com/perforce/doc.current/manuals/p4sag/index.html
                Requires=network.target network-online.target
                After=network.target network-online.target

                [Service]
                Type=forking
                TimeoutStartSec=60s
                TimeoutStopSec=60s
                ExecStart=/p4/1/bin/p4d_1_init start
                ExecStop=/p4/1/bin/p4d_1_init stop
                User=p4admin

                [Install]
                WantedBy=multi-user.target
              mode: "000400"
              owner: "p4admin"
              group: "perforce"
          commands:
            01_enable_daemon:
              command: "systemctl enable p4d_1"
              ignoreErrors: false
            02_start_daemon:
              command: "systemctl start p4d_1"
              ignoreErrors: false
            03_configure_server:
              command: "/hxdepots/sdp/Server/setup/configure_new_server.sh 1"
              ignoreErrors: false
  VolumeHxlogs:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-northeast-1a
      Size: '128'
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: p4-awsnva-01-hxlogs
      - Key: ServerID
        Value: master.1
  VolumeHxdepots:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-northeast-1a
      Encrypted: true
      Size: '1024'
      VolumeType: st1
      Tags:
      - Key: ServerID
        Value: master.1
      - Key: Name
        Value: p4-awsnva-01-hxdepots
  VolumeHxmetadata:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-northeast-1a
      Size: '64'
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: p4-awsnva-01-hxmetadata
      - Key: ServerID
        Value: master.1
  sgPerforceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This security group is for Perforce.
      VpcId:
        Ref: vpc089014ea9c553180d
  acl1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId:
        Ref: acl0dc84171401f0d22f
  acl2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId:
        Ref: acl0dc84171401f0d22f
  subnetacl1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: acl0dc84171401f0d22f
      SubnetId:
        Ref: subnet04731f3d427d1b04f
  gw1:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: vpc089014ea9c553180d
      InternetGatewayId:
        Ref: igw06ff7ac884deea506
  route1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: rtb04fd13c1658e30807
      GatewayId:
        Ref: igw06ff7ac884deea506
    DependsOn: gw1
  subnetrtbassoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: rtb04fd13c1658e30807
      SubnetId:
        Ref: subnet04731f3d427d1b04f
  dchpassoc1:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId:
        Ref: vpc089014ea9c553180d
      DhcpOptionsId:
        Ref: dopt06d06862
  assoc1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::GetAtt:
        - eip1817754170
        - AllocationId
      InstanceId:
        Ref: instancei094428780f474b671
  ingress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
  ingress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      CidrIp: 0.0.0.0/0
  ingress3:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: tcp
      FromPort: '1666'
      ToPort: '1666'
      CidrIp: 0.0.0.0/0
  egress1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Ref: sgPerforceSG
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
Description: Perforce-server
